info:
  build:
    name: @project.artifactId@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@

server:
  port: 8082

endpoints:
  enabled: true
  sensitive: false

data:
  test:
    envName: pro
    envconfig: 127.0.0.1:8082